kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-n-exec
  labels:
    type: local
spec:
  capacity:
    storage: 150M
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/k8s
    server: 10.128.0.3
    readOnly: false
